// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Credenciales reales de Firebase
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4sHUrfFxd8WTNo75KDRUzOAMIohhmgPI',
    appId: '1:837321484025:web:tu-web-app-id', // Se configurará cuando agregues la app web
    messagingSenderId: '837321484025',
    projectId: 'parchis-reverse-app',
    authDomain: 'parchis-reverse-app.firebaseapp.com',
    databaseURL: 'https://parchis-reverse-app-default-rtdb.firebaseio.com',
    storageBucket: 'parchis-reverse-app.firebasestorage.app',
    measurementId: 'TU_MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4sHUrfFxd8WTNo75KDRUzOAMIohhmgPI',
    appId: '1:837321484025:android:859d0b836998587c892428',
    messagingSenderId: '837321484025',
    projectId: 'parchis-reverse-app',
    databaseURL: 'https://parchis-reverse-app-default-rtdb.firebaseio.com',
    storageBucket: 'parchis-reverse-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4sHUrfFxd8WTNo75KDRUzOAMIohhmgPI',
    appId: '1:837321484025:ios:tu-ios-app-id', // Se configurará cuando agregues la app iOS
    messagingSenderId: '837321484025',
    projectId: 'parchis-reverse-app',
    databaseURL: 'https://parchis-reverse-app-default-rtdb.firebaseio.com',
    storageBucket: 'parchis-reverse-app.firebasestorage.app',
    iosBundleId: 'com.example.parchisReverseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4sHUrfFxd8WTNo75KDRUzOAMIohhmgPI',
    appId: '1:837321484025:macos:tu-macos-app-id', // Se configurará cuando agregues la app macOS
    messagingSenderId: '837321484025',
    projectId: 'parchis-reverse-app',
    databaseURL: 'https://parchis-reverse-app-default-rtdb.firebaseio.com',
    storageBucket: 'parchis-reverse-app.firebasestorage.app',
    iosBundleId: 'com.example.parchisReverseApp',
  );
}